version: "3.5"

services:
  api01: &api
    image: adolfoweloy/galoindio
    container_name: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
  api02:
    <<: *api
    container_name: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024-q1
